version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-painel2px
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 010203
      POSTGRES_DB: painel2px
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do contêiner para a porta 5432 do host
    restart: always